### ISSUE TITLE
wall_timer.cpp.o: file not recognized: File truncated when compiling roscpp

### ISSUE THREAD

**Issue by rnunziata** [ROSbots/rosbots_setup_tools#1]
I am getting the following error when running . Any help with this...I increased my sway space to 1024 does not help.
fab main_setup_ros_opencv_for_rosbots --host dex.local
FYI: the command line you give in readme is not correct but should be as above.

```

[dex.local] out: [ 33%] Linking CXX shared library /home/pi/ros_catkin_ws/devel_isolated/roscpp/lib/libroscpp.so
[dex.local] out: CMakeFiles/roscpp.dir/src/libros/wall_timer.cpp.o: file not recognized: File truncated
[dex.local] out: collect2: error: ld returned 1 exit status
[dex.local] out: CMakeFiles/roscpp.dir/build.make:1317: recipe for target '/home/pi/ros_catkin_ws/devel_isolated/roscpp/lib/libroscpp.so' failed
[dex.local] out: make[2]: *** [/home/pi/ros_catkin_ws/devel_isolated/roscpp/lib/libroscpp.so] Error 1
[dex.local] out: CMakeFiles/Makefile2:82: recipe for target 'CMakeFiles/roscpp.dir/all' failed
[dex.local] out: make[1]: *** [CMakeFiles/roscpp.dir/all] Error 2
[dex.local] out: Makefile:138: recipe for target 'all' failed
[dex.local] out: make: *** [all] Error 2
[dex.local] out: <== Failed to process package 'roscpp': 
[dex.local] out:   Command '['/home/pi/ros_catkin_ws/build/opt/ros/kinetic/env.sh', 'make', '-j2']' returned non-zero exit status 2
[dex.local] out: 
[dex.local] out: Reproduce this error by running:
[dex.local] out: ==> cd /home/pi/ros_catkin_ws/build_isolated/roscpp && /home/pi/ros_catkin_ws/build/opt/ros/kinetic/env.sh make -j2
[dex.local] out: 
[dex.local] out: Command failed, exiting.
[dex.local] out: 


Fatal error: run() received nonzero return code 1 while executing!

Requested: ./src/catkin/bin/catkin_make_isolated --install -DCMAKE_BUILD_TYPE=Release --install-space /home/pi/ros_catkin_ws/build/opt/ros/kinetic -j2
Executed: /bin/bash -l -c "cd /home/pi/ros_catkin_ws >/dev/null && ./src/catkin/bin/catkin_make_isolated --install -DCMAKE_BUILD_TYPE=Release --install-space /home/pi/ros_catkin_ws/build/opt/ros/kinetic -j2"

```

**Comment by rnunziata** [comment]
I was able to get ros up and running but I still can not completely run though the whole of the setup as it keeps error-ing out with different errors. Not sure why this is because the errors are very different from each but seem to happen on the install step.  Eventually I got enough installed so as to be able to run.

**Comment by TheGalacticHero** [comment]
http://wiki.ros.org/ROSberryPi/Installing%20ROS%20Kinetic%20on%20the%20Raspberry%20Pi

I did this after days of errors.  Working fine.

**Comment by rnunziata** [comment]
I was able to install using indigo only kinetic had some compile error related to lisp even when excluded in directive

**Comment by TheGalacticHero** [comment]
Were you using Fab?  I think that may be the problem.  Go to the terminal on the Pi and try the procedure on the link above.  If you've already tried and had an abort you might have to scrub the disk and start over, but, after 20 tries of various ways through Fab over 60 hours, the procedure on that wiki worked on the first try.  I have no idea what to do from there, but listing the nodes works.  I didn't install the gui version, someone might try that, I guess.

**Comment by jackpien** [comment]
I can't seem to reproduce this error.  I just used a new 2017-07-05 Raspbian Lite image - https://downloads.raspberrypi.org/raspbian_lite_latest - and running 

> fab -H x.x.x.x main_setup_ros_opencv_for_rosbots

works perfectly.
