### ISSUE TITLE
error at the end of setup

### ISSUE THREAD

**Issue by ghost** [ROSbots/rosbots_setup_tools#2]
Hello,

I got an error like:
`[192.168.0.34] out:               
[192.168.0.34] out: 100% [Packages 0 B]
[192.168.0.34] out:                    
[192.168.0.34] out: 100% [Working]
[192.168.0.34] out:               
[192.168.0.34] out: 100% [Packages 0 B]
[192.168.0.34] out:                    
[192.168.0.34] out: 100% [Working]
[192.168.0.34] out:               
[192.168.0.34] out: 

Fatal error: sudo() received nonzero return code -1 while executing!

Requested: apt-get update
Executed: sudo -S -p 'sudo password:'  /bin/bash -l -c "apt-get update"

Aborting.
Disconnecting from 192.168.0.34... done.`

however when I ssh into the raspi, i see that roscore is running, and topics are listed.

Is this an actual error? At what stage of the setup did this error happen?

Any recomendations most welcome,

Best,
C.

**Comment by TheGalacticHero** [comment]
I got the same error many times, and I feel a broken record, but this worked for me:
http://wiki.ros.org/ROSberryPi/Installing%20ROS%20Kinetic%20on%20the%20Raspberry%20Pi

**Comment by jackpien** [comment]
For reasons that are not clear to me, the apt-get update in step_4_setup_opencv_for_pi() causes:

> Fatal error: sudo() received nonzero return code -1 while executing!
> 
> Requested: apt-get update
> Executed: sudo -S -p 'sudo password:'  /bin/bash -l -c "apt-get update"

The apt-get update is not necessary any so removing fixes the issue. Commit 6dfc68993007665eea679e6b43e472134fd731db
