### ISSUE TITLE
FIX FOR ISSUES

### ISSUE THREAD

**Issue by TheGalacticHero** [ROSbots/rosbots_setup_tools#3]
Assuming you can get the Pi up and running, this got ROS working for me:
http://wiki.ros.org/ROSberryPi/Installing%20ROS%20Kinetic%20on%20the%20Raspberry%20Pi

I used the non-gui version.

**Comment by jackpien** [comment]
For reasons that are not clear to me, the apt-get update in step_4_setup_opencv_for_pi() causes:

> Fatal error: sudo() received nonzero return code -1 while executing!
> 
> Requested: apt-get update
> Executed: sudo -S -p 'sudo password:'  /bin/bash -l -c "apt-get update"

The apt-get update is not necessary any so removing fixes the issue. Commit 6dfc68993007665eea679e6b43e472134fd731db
